/**
 * bridge-scripts.ts — Shell scripts injected into the VM at boot time.
 *
 * These overwrite /usr/local/bin/curl-bridge and /usr/local/bin/cast
 * so the IPC uses /ipc (dir-mounted IDBDevice) for VM->JS reads
 * and /data (DataDevice) for JS->VM response writes.
 */

/* eslint-disable no-useless-escape */

export const CURL_BRIDGE_SCRIPT = [
  '#!/bin/bash',
  '# curl-bridge.sh — curl replacement bridging HTTP through browser fetch()',
  '# Requests  -> /ipc/req_ID.json  (VM writes, JS reads via ipcDevice)',
  '# Responses -> /data/resp_ID.json (JS writes via dataDevice, VM reads)',
  '',
  'STOP_FILE="/tmp/bridge/stop"',
  '',
  '# Check stop flag',
  'if [ -f "$STOP_FILE" ]; then',
  '  echo \'{"error":{"message":"agent stopped"}}\' >&2',
  '  exit 1',
  'fi',
  '',
  '# Parse curl arguments',
  'METHOD="GET"',
  'URL=""',
  'BODY=""',
  'SILENT=0',
  'TIMEOUT=120',
  'declare -a HEADERS_KEYS=()',
  'declare -a HEADERS_VALS=()',
  '',
  'while [ $# -gt 0 ]; do',
  '  case "$1" in',
  '    -s)',
  '      SILENT=1',
  '      shift',
  '      ;;',
  '    -m)',
  '      TIMEOUT="$2"',
  '      shift 2',
  '      ;;',
  '    -X)',
  '      METHOD="$2"',
  '      shift 2',
  '      ;;',
  '    -H)',
  '      HDR="$2"',
  '      KEY="${HDR%%:*}"',
  '      VAL="${HDR#*: }"',
  '      HEADERS_KEYS+=("$KEY")',
  '      HEADERS_VALS+=("$VAL")',
  '      shift 2',
  '      ;;',
  '    -K)',
  '      HDRFILE="$2"',
  '      if [ -f "$HDRFILE" ]; then',
  '        while IFS= read -r line || [ -n "$line" ]; do',
  '          case "$line" in',
  '            -H\\ *)',
  '              HDR="${line#-H }"',
  '              HDR="${HDR#\\\"}"',
  '              HDR="${HDR%\\\"}"',
  '              KEY="${HDR%%:*}"',
  '              VAL="${HDR#*: }"',
  '              HEADERS_KEYS+=("$KEY")',
  '              HEADERS_VALS+=("$VAL")',
  '              ;;',
  '          esac',
  '        done < "$HDRFILE"',
  '      fi',
  '      shift 2',
  '      ;;',
  '    -d)',
  '      DATA="$2"',
  '      if [[ "$DATA" == @* ]]; then',
  '        BODYFILE="${DATA:1}"',
  '        BODYFILE="${BODYFILE%\\\'}"',
  '        BODYFILE="${BODYFILE#\\\'}"',
  '        BODYFILE="${BODYFILE%\\"}"',
  '        BODYFILE="${BODYFILE#\\"}"',
  '        if [ -f "$BODYFILE" ]; then',
  '          BODY=$(cat "$BODYFILE")',
  '        fi',
  '      else',
  '        BODY="$DATA"',
  '      fi',
  '      if [ "$METHOD" = "GET" ]; then',
  '        METHOD="POST"',
  '      fi',
  '      shift 2',
  '      ;;',
  '    -*)',
  '      if [ $# -gt 1 ] && [[ ! "$2" == -* ]] && [[ ! "$2" == http* ]]; then',
  '        shift 2',
  '      else',
  '        shift',
  '      fi',
  '      ;;',
  '    *)',
  '      URL="$1"',
  '      URL="${URL%\\\'}"',
  '      URL="${URL#\\\'}"',
  '      URL="${URL%\\"}"',
  '      URL="${URL#\\"}"',
  '      shift',
  '      ;;',
  '  esac',
  'done',
  '',
  'if [ -z "$URL" ]; then',
  '  echo "curl-bridge: no URL specified" >&2',
  '  exit 1',
  'fi',
  '',
  '# Generate unique request ID',
  'REQ_ID="req_$$_$(date +%s%N 2>/dev/null || echo $RANDOM)"',
  '',
  '# Build headers JSON object',
  'HEADERS_JSON="{"',
  'for i in "${!HEADERS_KEYS[@]}"; do',
  '  if [ "$i" -gt 0 ]; then HEADERS_JSON+=","; fi',
  '  K=$(printf \'%s\' "${HEADERS_KEYS[$i]}" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g\')',
  '  V=$(printf \'%s\' "${HEADERS_VALS[$i]}" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g\')',
  '  HEADERS_JSON+="\\"$K\\":\\"$V\\""',
  'done',
  'HEADERS_JSON+="}"',
  '',
  '# Write body to /ipc for JS to read',
  'BODY_FILE="/ipc/${REQ_ID}.body"',
  'printf \'%s\' "$BODY" > "$BODY_FILE"',
  '',
  '# Write request JSON to /ipc',
  'cat > "/ipc/${REQ_ID}.json" << REQEOF',
  '{"id":"$REQ_ID","type":"http","method":"$METHOD","url":"$URL","headers":$HEADERS_JSON,"bodyFile":"/ipc/${REQ_ID}.body","timeout":$TIMEOUT}',
  'REQEOF',
  '',
  '# Signal request is ready',
  'touch "/ipc/${REQ_ID}.ready"',
  '',
  '# Poll for response from /data',
  'ELAPSED=0',
  'while [ $ELAPSED -lt $((TIMEOUT * 10)) ]; do',
  '  if [ -f "$STOP_FILE" ]; then',
  '    echo \'{"error":{"message":"agent stopped"}}\' >&2',
  '    rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" "$BODY_FILE" 2>/dev/null',
  '    exit 1',
  '  fi',
  '',
  '  if [ -f "/data/resp_${REQ_ID}.ready" ]; then',
  '    if [ -f "/data/resp_${REQ_ID}.json" ]; then',
  '      cat "/data/resp_${REQ_ID}.json"',
  '    fi',
  '    # Cleanup both /ipc and /data',
  '    rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" "$BODY_FILE" \\',
  '          "/data/resp_${REQ_ID}.json" "/data/resp_${REQ_ID}.ready" 2>/dev/null',
  '    exit 0',
  '  fi',
  '',
  '  sleep 0.1',
  '  ELAPSED=$((ELAPSED + 1))',
  'done',
  '',
  '# Timeout',
  'echo \'{"error":{"message":"curl-bridge: request timed out"}}\' >&2',
  'rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" "$BODY_FILE" 2>/dev/null',
  'exit 28',
].join('\n');

export const CAST_BRIDGE_SCRIPT = [
  '#!/bin/bash',
  '# cast-bridge.sh — cast replacement with smart routing',
  '# Requests  -> /ipc/req_ID.json  (VM writes, JS reads via ipcDevice)',
  '# Responses -> /data/resp_ID.json (JS writes via dataDevice, VM reads)',
  '',
  'STOP_FILE="/tmp/bridge/stop"',
  'CAST_NATIVE="/usr/local/bin/cast-native"',
  '',
  '# Check stop flag',
  'if [ -f "$STOP_FILE" ]; then',
  '  echo "Error: agent stopped" >&2',
  '  exit 1',
  'fi',
  '',
  '# Pure-compute subcommands — run native cast directly',
  'if [ -x "$CAST_NATIVE" ]; then',
  '  case "$1" in',
  '    sig|keccak|keccak256|abi-encode|abi-decode|--to-wei|--from-wei|--to-hex|--to-dec|--to-base|max-uint|max-int)',
  '      exec "$CAST_NATIVE" "$@"',
  '      ;;',
  '  esac',
  'fi',
  '',
  '# Network-dependent subcommands — bridge through browser',
  'REQ_ID="cast_$$_$(date +%s%N 2>/dev/null || echo $RANDOM)"',
  '',
  '# Build JSON args array',
  'ARGS_JSON="["',
  'FIRST=1',
  'for arg in "$@"; do',
  '  if [ "$FIRST" -eq 0 ]; then ARGS_JSON+=","; fi',
  '  FIRST=0',
  '  ESCAPED=$(printf \'%s\' "$arg" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g; s/\\t/\\\\t/g; s/\\n/\\\\n/g\')',
  '  ARGS_JSON+="\\"$ESCAPED\\""',
  'done',
  'ARGS_JSON+="]"',
  '',
  '# Write request to /ipc',
  'cat > "/ipc/${REQ_ID}.json" << REQEOF',
  '{"id":"$REQ_ID","type":"cast","args":$ARGS_JSON}',
  'REQEOF',
  '',
  '# Signal ready',
  'touch "/ipc/${REQ_ID}.ready"',
  '',
  '# Poll for response from /data (120s timeout)',
  'TIMEOUT=120',
  'ELAPSED=0',
  'while [ $ELAPSED -lt $((TIMEOUT * 10)) ]; do',
  '  if [ -f "$STOP_FILE" ]; then',
  '    echo "Error: agent stopped" >&2',
  '    rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" 2>/dev/null',
  '    exit 1',
  '  fi',
  '',
  '  if [ -f "/data/resp_${REQ_ID}.ready" ]; then',
  '    if [ -f "/data/resp_${REQ_ID}.json" ]; then',
  '      cat "/data/resp_${REQ_ID}.json"',
  '    fi',
  '    # Cleanup',
  '    rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" \\',
  '          "/data/resp_${REQ_ID}.json" "/data/resp_${REQ_ID}.ready" 2>/dev/null',
  '    exit 0',
  '  fi',
  '',
  '  sleep 0.1',
  '  ELAPSED=$((ELAPSED + 1))',
  'done',
  '',
  'echo "Error: cast bridge request timed out" >&2',
  'rm -f "/ipc/${REQ_ID}.json" "/ipc/${REQ_ID}.ready" 2>/dev/null',
  'exit 1',
].join('\n');
